/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    ACascader: typeof import('ant-design-vue/es')['Cascader']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AntCom: typeof import('./src/components/AntCom.vue')['default']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATimePicker: typeof import('ant-design-vue/es')['TimePicker']
    ATransfer: typeof import('ant-design-vue/es')['Transfer']
    ATreeSelect: typeof import('ant-design-vue/es')['TreeSelect']
    BooCom: typeof import('./src/components/BooCom.vue')['default']
    EleCom: typeof import('./src/components/EleCom.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LangBar: typeof import('./src/components/LangBar.vue')['default']
    NaiCom: typeof import('./src/components/NaiCom.vue')['default']
    QuaCom: typeof import('./src/components/QuaCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
